### PR TITLE
Add a guide on deploying Yesod to Heroku.

### PR DESCRIPTION
**Pull request by StevenXL**

### CODE REVIEW

**Comment by bitemyapp** [comment]
You've exercised all this recently? My main hesitation w/ Heroku would be that this is docs that can fall out of date easily with no CI feedback. I also had the impression that people weren't paying as much attention to Heroku of late, but that could be a self-selected niche I inhabit.

**Comment by StevenXL** [comment]
Hi Chris - 

Yes, I exercised all of this in the past 2 weeks. I have an app running in production based off of these directions, and the post is as much for others to consume as for me to not forget the details.

I would hate to put something out there that wastes someone's time if things were to break. Would your concern be alleviated if I put the scaffolded site up onto a few heroku dyno, and added CI to that. (Note that I don't know what steps constitute "add CI to that", but I'm willing to learn). 

Let me know.

**Comment by psibi** [comment]
@bitemyapp I think this is good to have it even if it becomes a little outdated. I will go ahead and merge if you don' have any concern.

**Comment by psibi** [comment]
@bitemyapp I have gone ahead and merged this as I feel it's good to have this even it becomes outdated. It would be easy for others to improve an existing broken documentation rather having no documentation.

**Pull request merged**
