### PR TITLE
Create Maintaining-Applicative-Form-Behavior-In-Monadic-Forms.md

### PR DESCRIPTION
**Pull request by joelmccracken**

### CODE REVIEW

**Comment by joelmccracken** [comment]
Fixes #49

**Comment by psibi** [comment]
@joelmccracken Thanks! Sorry for getting back to you a little late. Can you make this as an self contained example like this: https://github.com/yesodweb/yesod-cookbook/blob/master/snippets/Basic_Template.md ?

**Comment by joelmccracken** [comment]
ah, so you mean like making it an entire actual example/fully reproducible as opposed to being a small chunk of code without the supporting app code around it?

**Comment by psibi** [comment]
@joelmccracken Yes, It can be still a small example - but if it's an working snippet, that's much more helpful.

**Comment by joelmccracken** [comment]
Great idea! I will do so

**Comment by joelmccracken** [comment]
Lol, sorry i have forgotten about this for forever. I'll try to do it tonight

**Comment by psibi** [comment]
I'm merging this as this is useful in it's current form. This can be refined further to address other comments in the later PR's.

**Pull request merged**
