### PR TITLE
Subsite with typeclass contexts and type variables

### PR DESCRIPTION
**Pull request by jprider63**
I wasn't sure what category to add this to, but "Routing" seemed to make the most sense. Is there anything else you'd like me to add?

### CODE REVIEW

**Comment by psibi** [comment]
@jprider63 I will merge this once your code is merged there. Thanks!

**Comment by ajnsit** [comment]
This will be great for [wai-routes](https://github.com/ajnsit/wai-routes) as well. Since subsites currently use typeclass definitions, but this would help them go the other way round (i.e. use simple types).

**Comment by psibi** [comment]
@jprider63 Is there any motivation for having typeclass contexts and  type variables ?

**Comment by jprider63** [comment]
My use case is I'm writing a subsite where the types are dependent on the parent site. I've written more about it in this [post](https://groups.google.com/forum/#!topic/yesodweb/DTDcDPT7Wps) and this issue (yesodweb/yesod#1365).

**Comment by psibi** [comment]
Thanks!

**Pull request merged**
