### PR TITLE
Add topic on Custom data types column in Persistent

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by psibi** [comment]
@snoyberg Is serializing and Unserializing like this recommended or is there some other better way to achieve the same ?

**Comment by snoyberg** [comment]
It's bad from a DB management standpoint: it's just storing the data as JSON in the table, which is difficult to work with. The proper where is to just have two different fields in the entity. Whether you want to do it one way or the other though is up to personal preference, both work.

**Comment by psibi** [comment]
Note that it's not storing the data as JSON but as a list string in the database. But yeah, it's bad for writing DB queries. I will add up your comment in the page.

**Comment by psibi** [comment]
Ah, you are right. It's storing as JSON.

**Pull request merged**
